<center> <h1> Google Maps API </h> </center> 
<center> <h2> Homework 1 </h> </center> 
<center> <h3> Data Preprocessing </h> </center>

A. Use the [*Nearby Seach*](https://developers.google.com/places/web-service/search) Method to find all the restaurant near to the UPY (20.988459, -89.736768) around 2km. In order to fulfill this item you need to:
* Create a *search_nearby_places* function with the appropiate parameters. It must return a JSON with the results. Places must be ranked by distance.
* Create a table with the following columns: Name, Place Id, Rating, Place Types, Total of User Ratings.

In [1]:
import requests
import json
import pandas as pd

In [2]:
# Parameters

location='20.988459,-89.736768' # UPY coordinates
radius=2000
place_type='restaurant'# We are looking for nearby restaurants 
key='AIzaSyAVelLKw0edLedq4i9IU1abn8rXuV3ep8k'

In [3]:
#Define search_nearby_places() function

def search_nearby_places(location, radius, place_type, key):
    """
    Function that makes an API request and returns a dictionary containing nearby places
    -----------------------------
    Input: 
        <string>
            
            'location' : a string in the form 'lat,lon'
            'place_type' : a string containing the place type(s) separated by commas
            'key' : your API key
            
        <int>
            
            'radius' : in meters
    -----------------------------
    Output: 
        
        <json dictionary> containing information about nearby places to the given location
        
    """
    
    endpoint_url='https://maps.googleapis.com/maps/api/place/nearbysearch/json'
    
    # Establish parameters
    
    parameters = {
        'key' : key, 
        'location' : location, 
        'radius' : radius, #Note that radius must not be included if rankby=distance
        'type' : place_type, 
        #'rankby' : rankby #Note that rankby must not be included if radius is specified.
    }

    res = requests.get(endpoint_url, params = parameters) #Get the data aplying the designed parameters
    
    res.content #Read it as an object
    
    results = json.loads(res.content) # Read as dict
    
    return results #Return json as a dict

In [4]:
json_dict = search_nearby_places(location, radius, place_type, key)

In [5]:
json_dict_dt=pd.read_json(json.dumps(json_dict['results']), orient='record') #parsing according to a 'records' structure, json.dumps() to convert the dict into a json

In [6]:
restaurants = json_dict_dt[['name', 'place_id', 'rating', 'types', 'user_ratings_total']] # Use the following columns for the table

restaurants

,name,place_id,rating,types,user_ratings_total
0,La Glorieta (Cocina y Pizzería),ChIJC9i7XEsNVo8Ro2-sdS45rBg,4.1,"[restaurant, food, point_of_interest, establis...",14.0
1,Mr. Cazuelas,ChIJ3WHHeJkMVo8RO_z2pfoDFZg,4.0,"[restaurant, food, point_of_interest, establis...",3.0
2,El Rincón Del Tabas,ChIJn4UFHpwMVo8RZOfFHQCuIwo,5.0,"[restaurant, food, point_of_interest, establis...",2.0
3,Moyoyos burger,ChIJqxQ91h0NVo8R52sc8a1HlvE,NaN,"[restaurant, food, point_of_interest, establis...",NaN
4,"Cocina economica ""El sabor de doña antonia""",ChIJaQJm928NVo8RAN8mnDmvYEk,NaN,"[restaurant, food, point_of_interest, establis...",NaN
5,Cemitas Poblanas Doña Dulce,ChIJ-18misANVo8R8_gP-uVUAMY,4.8,"[restaurant, food, point_of_interest, establis...",21.0
6,Hamburguesas Maaaa de la 112.,ChIJXTh3gaoNVo8RovFdjQ-lN10,3.7,"[restaurant, food, point_of_interest, establis...",6.0
7,Carnívoros,ChIJx9nxwp0MVo8RvujKFHXH6H4,4.1,"[restaurant, food, point_of_interest, establis...",39.0
8,Modelorama,ChIJozhU3J0MVo8RKZTNG5qZyu4,4.8,"[convenience_store, bar, liquor_store, restaur...",4.0
9,La BOMBA DEL SABOR,ChIJXzbguNgLVo8RnxttdBhYakc,5.0,"[restaurant, food, point_of_interest, establis...",2.0
10,La Carlota,ChIJVWRJiW8NVo8R7E46087W96E,5.0,"[meal_delivery, restaurant, food, point_of_int...",4.0
11,The witch burgers,ChIJk8-rWwgNVo8RhVnpRaHabZ8,5.0,"[restaurant, food, point_of_interest, establis...",1.0
12,Panuchos & Salbutes El Almendrito,ChIJ80ttQuMLVo8RC-oH1Eisi8A,5.0,"[restaurant, food, point_of_interest, establis...",1.0
13,HAMBURGUESAS HARAMYYU BIRIZ,ChIJHdPcMX0LVo8RhSB1GURFT7U,NaN,"[restaurant, food, point_of_interest, establis...",NaN
14,PerryBurguer,ChIJldA29UgLVo8Rj6HAXz7I2iM,4.5,"[restaurant, food, point_of_interest, establis...",10.0

B. Create a function to Find the Place Id given Place Name (String) and Location (Lat/Lont Tuple).

In [7]:
#Using Text Search Request Method
def find_place_request(place_name, location, key):
    """
    Function that takes a text input, and returns a place.
    ----------------------
    Input:
        <string>
        
        'place_name' : The text input can be any kind of Places data, for example, a name, address, or phone number.
        'key' : your API key
        'location' : in the form 'lat,lon'
    -------------------------
    Output:
        <json dictionary> containing information about a place
    """
    
    if type(location)!=str:
        location=str(location[0])+','+str(location[1])
        
    endpoint_url='https://maps.googleapis.com/maps/api/place/findplacefromtext/json'
    
    # Establish parameters
    
    locationbias='circle:100@'+location
    
    parameters = {
        'input' : place_name,
        'inputtype' : 'textquery',
        'key' : key,
        'locationbias' : locationbias,
        'fields' : 'name,place_id'
    }
    
    res = requests.get(endpoint_url, params = parameters) #Get the data aplying the designed parameters
    
    res.content #Read it as an object
    
    results = json.loads(res.content) # Read as dict
    
    print(results)
    
    return results['candidates'][0]['place_id'] # Return the firs candidate (which is the nearest to that coordinate)

In [8]:
pruebita = find_place_request('Starbucks Montejo', '20.984937,-89.617909', key)

{'candidates': [{'name': 'Starbucks', 'place_id': 'ChIJaUUfylFxVo8RgEGjoansPbc'}], 'status': 'OK'}

In [9]:
pruebita

'ChIJaUUfylFxVo8RgEGjoansPbc'

C. Find the Place ID of the following places using your functions:
* McCarthy's Irish Pub - Caucel
* Starbucks Montejo
* Los Trompos Circuito

In [10]:
#Target locations (an estimation) using Google Maps
McCarthys_aproximation='20.999950,-89.682548'
Starbucks_aproximation='20.984937,-89.617909'
Trompos_aproximation='20.998842,-89.617407'

In [11]:
McCarthys_id=find_place_request("McCarthy's Irish Pub - Caucel", McCarthys_aproximation, key)
print("McCarthys_id:", McCarthys_id)

{'candidates': [{'name': "McCarthy's Irish Pub - Caucel", 'place_id': 'ChIJJyKKOKB0Vo8RCQcxkUw6hp8'}], 'status': 'OK'}
McCarthys_id: ChIJJyKKOKB0Vo8RCQcxkUw6hp8

In [12]:
Starbucks_id=find_place_request('Starbucks Montejo', Starbucks_aproximation, key)
print("Starbucks_id:", Starbucks_id)

{'candidates': [{'name': 'Starbucks', 'place_id': 'ChIJaUUfylFxVo8RgEGjoansPbc'}], 'status': 'OK'}
Starbucks_id: ChIJaUUfylFxVo8RgEGjoansPbc

In [13]:
Trompos_id=find_place_request('Los Trompos Circuito',Trompos_aproximation, key)
print("Trompos_id:", Trompos_id)

{'candidates': [{'name': 'Los Trompos', 'place_id': 'ChIJpVKXOq12Vo8RK4bUWILT9dI'}], 'status': 'OK'}
Trompos_id: ChIJpVKXOq12Vo8RK4bUWILT9dI

D. Use the [*Place Details*](https://developers.google.com/places/web-service/details#PlaceDetailsResults) Method to find the Reviews of a Place in English and Spanish. In order to fulfill this item you need to:
* Create a *find_reviews* function with the appropiate parameters. It must return a JSON with the results. 
* Create a table with the following columns: Author Name, Language, Rating, Text, Time.

In [14]:
def find_reviews(place_id, key):
    """
    Function that takes a place_id and returns a json dictionary with that place reviews in english and spanish
    ----------------
    Input:
        <string>
            'place_id' : the place ID
            'key' : your API key
    ----------------
    Output:
        <json dictionary> contaning the place reviews
        
    """
        
    endpoint_url='https://maps.googleapis.com/maps/api/place/details/json'
    
    # Establish parameters
    
    parameters = {
        'key' : key,
        'place_id' : place_id,
        'language' : 'en,es'
    }
    
    res = requests.get(endpoint_url, params = parameters) #Get the data aplying the designed parameters
    
    res.content #Read it as an object
    
    results = json.loads(res.content) # Read as dict
    
    return results # Return the firs candidate (which is the nearest to that coordinate)

In [15]:
starbucks = find_reviews('ChIJaUUfylFxVo8RgEGjoansPbc', key)

In [16]:
starbucks_dt = pd.read_json(json.dumps(starbucks['result']['reviews']), orient='records')

In [17]:
starbucks_dt.columns

Index(['author_name', 'author_url', 'language', 'profile_photo_url', 'rating',
       'relative_time_description', 'text', 'time'],
      dtype='object')

In [18]:
starbucks_dt = starbucks_dt[['author_name','language','rating','text', 'time']]

In [19]:
#starbucks_dt = starbucks_dt.loc[(starbucks_dt['language']=='en') | (starbucks_dt['language']=='es')]
starbucks_dt

,author_name,language,rating,text,time
0,Brandy Campbell,en,5,They are always so fast and very polite. I'm a...,1558744858
1,J T,en,4,Lovely place. Good service. I have one request...,1543268696
2,Amy King,en,4,Lots of space in this two story starbucks,1560620959
3,James Wilson,en,3,I am Canadian and rarely visit Starbucks anywh...,1544219879
4,holly hunter,en,5,Great location and architecture!\nNice vibe in...,1550781744

E. Find similar places to Los Trompos Circuito. Rank them by its "Prominence". In order to fulfill this item you need to:
* Create a *find_similar* function with the appropiate parameters. It must return a JSON with the results.
* Create a table with the following columns: Place Name, Plaece Id, Rating, Total of Use Ratings.

In [20]:
def find_similar(location, radius, place_type, key):
    """
    Function that gets a specific location in a given radius and returns the most prominent places
    ------------------
    Input: <string>
            'location' : in the form 'lat,lon'
            'place_type' : for example 'restaurant'
            'key' : your API key
    -------------------
    Output: 
        <json dictionary> containing a list of the most prominent places and its information
    
    """
    
    endpoint_url='https://maps.googleapis.com/maps/api/place/nearbysearch/json'
    
    # Establish parameters
    
    parameters = {
        'key' : key, 
        'location' : location, 
        'radius' : radius, #Note that radius must not be included if rankby=distance
        'type' : place_type, 
        'rankby' : 'prominence' #Prominence
    }

    res = requests.get(endpoint_url, params = parameters) #Get the data aplying the designed parameters
    
    res.content #Read it as an object
    
    results = json.loads(res.content) # Read as dict
    
    return results #Return json as a dict

In [21]:
similar_to_trompos = find_similar('20.998842,-89.617407',500,'restaurant',key)

In [22]:
similar_to_trompos = pd.read_json(json.dumps(similar_to_trompos['results']), orient='records')
similar_to_trompos=similar_to_trompos[['name', 'place_id', 'rating', 'types', 'user_ratings_total']]
similar_to_trompos

,name,place_id,rating,types,user_ratings_total
0,Los Trompos,ChIJpVKXOq12Vo8RK4bUWILT9dI,4.5,"[restaurant, food, point_of_interest, establis...",3105.0
1,Mi Viejo Molino,ChIJA2XvLq12Vo8RmHzVkbC-a1M,4.2,"[restaurant, food, point_of_interest, establis...",1379.0
2,Pizza del Perro Negro,ChIJS67Ey6x2Vo8RTiTblDl7VT0,4.4,"[restaurant, food, point_of_interest, establis...",1776.0
3,Mr. Pampas,ChIJE1CvhrJ2Vo8RF6OCmqVdXjU,4.6,"[restaurant, food, point_of_interest, establis...",3903.0
4,A la pimienta,ChIJ_7yIt7J2Vo8ROAqvR1B2Ivc,4.5,"[bar, restaurant, food, point_of_interest, est...",255.0
5,Los Originales Tacos de Res,ChIJScV8m1JxVo8RGtH_DNMAHcs,4.5,"[restaurant, food, point_of_interest, establis...",33.0
6,Osteria Piccoli,ChIJ8cAMZLJ2Vo8RzqIacVgeGAU,4.7,"[restaurant, food, point_of_interest, establis...",315.0
7,Burger King,ChIJY9x1Tq12Vo8RJcAtqpexutk,4.1,"[restaurant, food, point_of_interest, establis...",2360.0
8,Muelle 8,ChIJY7vsm8Z2Vo8RJI7plSxAcmc,4.5,"[restaurant, food, point_of_interest, establis...",196.0
9,McCarthy's,ChIJAQMIqrJ2Vo8RyNB-NE2HXFw,4.5,"[bar, restaurant, food, point_of_interest, est...",3143.0
10,Trotter's,ChIJgbGOKq12Vo8RqhK2SdKJzdQ,4.6,"[restaurant, food, point_of_interest, establis...",654.0
11,Mago's Restaurante,ChIJK3zxq3N3Vo8R2ggPcP6c71c,5.0,"[restaurant, food, point_of_interest, establis...",2.0
12,Little Caesars Pizza,ChIJF4Txyqx2Vo8RcCd1I-3_uDg,4.1,"[meal_takeaway, restaurant, food, point_of_int...",457.0
13,Wings Wagon,ChIJe2eMV01xVo8RrEnoQoPqBq0,NaN,"[restaurant, food, point_of_interest, establis...",NaN
14,Taqueria Los Tortuguitas,ChIJd08xvLJ2Vo8RiZjcLRcE3pg,NaN,"[restaurant, food, point_of_interest, establis...",NaN
15,Tacos Doña Chona,ChIJfSFOZBl3Vo8RMKSzmbuK8-0,NaN,"[restaurant, food, point_of_interest, establis...",NaN
16,Cocina Esquinita Buenavista,ChIJIdADAztxVo8RnW7LfxOznss,4.4,"[restaurant, food, point_of_interest, establis...",9.0
17,RIEH,ChIJe9SSha12Vo8R4duZuE3Cc5c,4.5,"[restaurant, food, point_of_interest, establis...",93.0
18,ChichenTitlan Kekas,ChIJBVLY48N3Vo8RxIiZooRahC8,NaN,"[restaurant, food, point_of_interest, establis...",NaN
19,Zhen Liying,ChIJq6qq-lJxVo8RaQ2CCowNCUk,3.5,"[restaurant, food, point_of_interest, establis...",4.0

F. Complete all the above tasks but using the Python [GoogleMaps](https://github.com/googlemaps/google-maps-services-python) Library. [Here](https://googlemaps.github.io/google-maps-services-python/docs/#module-googlemaps) you can find the documentation.

In [23]:
import googlemaps

gmaps = googlemaps.Client(key='AIzaSyAVelLKw0edLedq4i9IU1abn8rXuV3ep8k') # Load the API key

In [24]:
# Function to search nearby places given a location, radius and type 
places = gmaps.places_nearby(location='20.988459,-89.736768',radius=2000, type='restaurant') # Input parameters

In [25]:
places = pd.read_json(json.dumps(places['results']), orient='record') # Accessing to the dictionary

In [26]:
places=places[['name', 'place_id', 'rating', 'types', 'user_ratings_total']] # Selecting target columns

In [27]:
places # Nearby places to the UPY

,name,place_id,rating,types,user_ratings_total
0,La Glorieta (Cocina y Pizzería),ChIJC9i7XEsNVo8Ro2-sdS45rBg,4.1,"[restaurant, food, point_of_interest, establis...",14.0
1,Mr. Cazuelas,ChIJ3WHHeJkMVo8RO_z2pfoDFZg,4.0,"[restaurant, food, point_of_interest, establis...",3.0
2,El Rincón Del Tabas,ChIJn4UFHpwMVo8RZOfFHQCuIwo,5.0,"[restaurant, food, point_of_interest, establis...",2.0
3,Moyoyos burger,ChIJqxQ91h0NVo8R52sc8a1HlvE,NaN,"[restaurant, food, point_of_interest, establis...",NaN
4,"Cocina economica ""El sabor de doña antonia""",ChIJaQJm928NVo8RAN8mnDmvYEk,NaN,"[restaurant, food, point_of_interest, establis...",NaN
5,Cemitas Poblanas Doña Dulce,ChIJ-18misANVo8R8_gP-uVUAMY,4.8,"[restaurant, food, point_of_interest, establis...",21.0
6,Hamburguesas Maaaa de la 112.,ChIJXTh3gaoNVo8RovFdjQ-lN10,3.7,"[restaurant, food, point_of_interest, establis...",6.0
7,Carnívoros,ChIJx9nxwp0MVo8RvujKFHXH6H4,4.1,"[restaurant, food, point_of_interest, establis...",39.0
8,Modelorama,ChIJozhU3J0MVo8RKZTNG5qZyu4,4.8,"[convenience_store, bar, liquor_store, restaur...",4.0
9,La BOMBA DEL SABOR,ChIJXzbguNgLVo8RnxttdBhYakc,5.0,"[restaurant, food, point_of_interest, establis...",2.0
10,La Carlota,ChIJVWRJiW8NVo8R7E46087W96E,5.0,"[meal_delivery, restaurant, food, point_of_int...",4.0
11,The witch burgers,ChIJk8-rWwgNVo8RhVnpRaHabZ8,5.0,"[restaurant, food, point_of_interest, establis...",1.0
12,Panuchos & Salbutes El Almendrito,ChIJ80ttQuMLVo8RC-oH1Eisi8A,5.0,"[restaurant, food, point_of_interest, establis...",1.0
13,HAMBURGUESAS HARAMYYU BIRIZ,ChIJHdPcMX0LVo8RhSB1GURFT7U,NaN,"[restaurant, food, point_of_interest, establis...",NaN
14,PerryBurguer,ChIJldA29UgLVo8Rj6HAXz7I2iM,4.5,"[restaurant, food, point_of_interest, establis...",10.0

In [28]:
# Function to find an specific place given a string containing the place name and its estimate location in a given radius
starbucks = gmaps.find_place(fields=['name','place_id'],input='Starbucks Montejo', location_bias='circle:100@20.984937,-89.617909', input_type='textquery')
starbucks

{'candidates': [{'name': 'Starbucks',
   'place_id': 'ChIJaUUfylFxVo8RgEGjoansPbc'}],
 'status': 'OK'}

In [29]:
trompos = gmaps.find_place(fields=['name','place_id'],input='Los Trompos Circuito', location_bias='circle:100@20.998842,-89.617407', input_type='textquery')
trompos

{'candidates': [{'name': 'Los Trompos',
   'place_id': 'ChIJpVKXOq12Vo8RK4bUWILT9dI'}],
 'status': 'OK'}

In [30]:
mcarthys = gmaps.find_place(fields=['name','place_id'],input="McCarthy's Irish Pub - Caucel", location_bias='circle:100@20.998842,-89.617407', input_type='textquery')
mcarthys

{'candidates': [{'name': "McCarthy's Irish Pub - Caucel",
   'place_id': 'ChIJJyKKOKB0Vo8RCQcxkUw6hp8'}],
 'status': 'OK'}

In [31]:
# Function that obtains place details in a given language
reviews = gmaps.place(place_id='ChIJJyKKOKB0Vo8RCQcxkUw6hp8', language='en,es') # ID from McCarthys

In [32]:
reviews=pd.read_json(json.dumps(reviews['result']['reviews']), orient='records') # Search for the reviews

In [33]:
reviews=reviews[['author_name','language','rating','text', 'time']] # Select the target columns

In [34]:
#reviews = reviews.loc[(reviews['language']=='en') | (reviews['language']=='es')]

In [35]:
reviews # McCarthys reviews

,author_name,language,rating,text,time
0,David Guillermo,en,3,They need person to regulate the sound inside ...,1566612760
1,Patrick,en,5,"One of the best pubs around.\nGreat service, g...",1518688093
2,Islas,en,5,"I love this place, one of the best places to d...",1522860496
3,Toni Aguilar,en,5,"Rockers, music lovers in general will enjoy th...",1516852970
4,monica ravell,en,5,Great place to listen to good rock,1531876412

In [36]:
# Function to find similar places ranked by its prominence given a location, radius and place type
similar_to_trompos = gmaps.places_nearby(location='20.998842,-89.617407',radius=500, type='restaurant', rank_by='prominence')

In [37]:
similar_to_trompos=pd.read_json(json.dumps(similar_to_trompos['results']), orient='records') # Finding places similar to Los Trompos

In [38]:
similar_to_trompos=similar_to_trompos[['name', 'place_id', 'rating', 'types', 'user_ratings_total']] # Target columns

In [39]:
similar_to_trompos # Places siimilar to Los Trompos by its prominence

,name,place_id,rating,types,user_ratings_total
0,Los Trompos,ChIJpVKXOq12Vo8RK4bUWILT9dI,4.5,"[restaurant, food, point_of_interest, establis...",3105.0
1,Mi Viejo Molino,ChIJA2XvLq12Vo8RmHzVkbC-a1M,4.2,"[restaurant, food, point_of_interest, establis...",1379.0
2,Pizza del Perro Negro,ChIJS67Ey6x2Vo8RTiTblDl7VT0,4.4,"[restaurant, food, point_of_interest, establis...",1776.0
3,Mr. Pampas,ChIJE1CvhrJ2Vo8RF6OCmqVdXjU,4.6,"[restaurant, food, point_of_interest, establis...",3903.0
4,A la pimienta,ChIJ_7yIt7J2Vo8ROAqvR1B2Ivc,4.5,"[bar, restaurant, food, point_of_interest, est...",255.0
5,Los Originales Tacos de Res,ChIJScV8m1JxVo8RGtH_DNMAHcs,4.5,"[restaurant, food, point_of_interest, establis...",33.0
6,Osteria Piccoli,ChIJ8cAMZLJ2Vo8RzqIacVgeGAU,4.7,"[restaurant, food, point_of_interest, establis...",315.0
7,Burger King,ChIJY9x1Tq12Vo8RJcAtqpexutk,4.1,"[restaurant, food, point_of_interest, establis...",2360.0
8,Muelle 8,ChIJY7vsm8Z2Vo8RJI7plSxAcmc,4.5,"[restaurant, food, point_of_interest, establis...",196.0
9,McCarthy's,ChIJAQMIqrJ2Vo8RyNB-NE2HXFw,4.5,"[bar, restaurant, food, point_of_interest, est...",3143.0
10,Trotter's,ChIJgbGOKq12Vo8RqhK2SdKJzdQ,4.6,"[restaurant, food, point_of_interest, establis...",654.0
11,Mago's Restaurante,ChIJK3zxq3N3Vo8R2ggPcP6c71c,5.0,"[restaurant, food, point_of_interest, establis...",2.0
12,Little Caesars Pizza,ChIJF4Txyqx2Vo8RcCd1I-3_uDg,4.1,"[meal_takeaway, restaurant, food, point_of_int...",457.0
13,Wings Wagon,ChIJe2eMV01xVo8RrEnoQoPqBq0,NaN,"[restaurant, food, point_of_interest, establis...",NaN
14,Taqueria Los Tortuguitas,ChIJd08xvLJ2Vo8RiZjcLRcE3pg,NaN,"[restaurant, food, point_of_interest, establis...",NaN
15,Tacos Doña Chona,ChIJfSFOZBl3Vo8RMKSzmbuK8-0,NaN,"[restaurant, food, point_of_interest, establis...",NaN
16,Cocina Esquinita Buenavista,ChIJIdADAztxVo8RnW7LfxOznss,4.4,"[restaurant, food, point_of_interest, establis...",9.0
17,RIEH,ChIJe9SSha12Vo8R4duZuE3Cc5c,4.5,"[restaurant, food, point_of_interest, establis...",93.0
18,ChichenTitlan Kekas,ChIJBVLY48N3Vo8RxIiZooRahC8,NaN,"[restaurant, food, point_of_interest, establis...",NaN
19,Zhen Liying,ChIJq6qq-lJxVo8RaQ2CCowNCUk,3.5,"[restaurant, food, point_of_interest, establis...",4.0

G. Create a Github Project as a Tutorial about How to Use the Google API. Don't forget to include a section with the set of instructions to obtain the Google API Key. In this tutorial, compare the use of the Google Maps [Places API] (https://developers.google.com/places/web-service/intro) and the Python [GoogleMaps](https://github.com/googlemaps/google-maps-services-python) Library using this activity tasks as examples.

## https://github.com/Tokiyomi/Google-Maps-API-for-dummies

## Checklist

| Task | Points |
|:----:|:------:|
|   Class Participation  |   10   |
|   a  |   10   |
|   b  |   10   |
|   c  |   10   |
|   d  |   10   |
|   e  |   10   |
|   f  |   20   |
|   g  |   20   |


* **Important!** Partial credit can be obteined in each task.
* Don not forget to document your functions! [Here](http://google.github.io/styleguide/pyguide.html) is the Python Programming Styleguide from Google. [Section 3.8](http://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings) is about Comments and Docstrings.
* To obtain the Class Participation Score you must complete an early submission with tasks: A, B and C.